# Generated by Django 3.0.14 on 2022-02-21 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0016_auto_20220221_1913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='DOB',
        ),
        migrations.RemoveField(
            model_name='student',
            name='sex',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='DOB',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='sex',
        ),
    ]
