# Generated by Django 3.0.14 on 2022-03-20 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0017_auto_20220221_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assigntime',
            name='period',
            field=models.CharField(choices=[('9:00 - 10:00', '9:00 - 10:00'), ('10:00 - 11:00', '10:00 - 11:00'), ('11:15 - 12:15', '11:15 - 12:15'), ('12:15 - 1:15', '12:15 - 1:15'), ('2:00 - 3:00', '2:00 - 3:00'), ('3:00 - 4:00', '3:00 - 4:00'), ('4:00 - 5:00', '4:00 - 5:00')], default='11:00 - 11:50', max_length=50),
        ),
    ]
